### ISSUE TITLE
Can't handle invalid/broken EXIF data

### ISSUE THREAD

**Issue by JohanG2012** [mb243/exifsort#5]
I had a few images with broken EXIF data. They had a value for when the photo was taken but this was not a valid date or valid ASCII characters instead it was these kinds of common random signs that you can see instead of Chinese text if you don't have a Chinese font installed for example. 

Unicode chart column D is the kind of the character I'm talking about:
https://en.wikipedia.org/wiki/Specials_(Unicode_block)

As a result, the script tried to create a folder with the name ".." (which is not possible) and started to move the pictures to that folder (which did not exist) so instead it seems like it ended up deleting all the pictures. 

Suggested solution: Make the script check if EXIF for when the photo was taken is valid date or valid ASCII and not ..

If it is to any help I can help recreate this bug, but I don't know how to fix this myself so I can't apply a fix on my own.

**Comment by mb243** [comment]
Can you run this on the file and provide the output as a codeblock for me?

`identify -verbose filename.jpg  | grep -i 'exif:datetime' | hexdump -C`

**Comment by mb243** [comment]
This is not going to be a straightforward fix, simply because data stored in exif fields can be stored in character sets other than ASCII. In your case, you're seeing Unicode, which is completely valid, but this script is going to fall over handling it, as you noticed.

The real solution would be to make this script character-set-aware, which is honestly more trouble than it's worth. An acceptable fix would be to detect non-ASCII data and handle it accordingly, but I don't have any images with that kind of data to test against.

In the meantime, I'd recommend taking a look at `exiftool` instead, which is character-set aware and pretty much does the job of this tool in a one-liner. Thanks for bringing this up, though.

**Comment by mb243** [comment]
If you can get back to me with that output, I'll try to add some parsing to at least catch those conditions.
